#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelRecordsMigrator.New
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="dev_tfs2.com")]
	public partial class NewDatabase : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCertificate(Certificate instance);
    partial void UpdateCertificate(Certificate instance);
    partial void DeleteCertificate(Certificate instance);
    partial void InsertMissionLog(MissionLog instance);
    partial void UpdateMissionLog(MissionLog instance);
    partial void DeleteMissionLog(MissionLog instance);
    partial void InsertMission(Mission instance);
    partial void UpdateMission(Mission instance);
    partial void DeleteMission(Mission instance);
    partial void InsertPage(Page instance);
    partial void UpdatePage(Page instance);
    partial void DeletePage(Page instance);
    partial void InsertPerson(Person instance);
    partial void UpdatePerson(Person instance);
    partial void DeletePerson(Person instance);
    partial void InsertPosition(Position instance);
    partial void UpdatePosition(Position instance);
    partial void DeletePosition(Position instance);
    partial void InsertQualification(Qualification instance);
    partial void UpdateQualification(Qualification instance);
    partial void DeleteQualification(Qualification instance);
    partial void InsertQualificationsCertificate(QualificationsCertificate instance);
    partial void UpdateQualificationsCertificate(QualificationsCertificate instance);
    partial void DeleteQualificationsCertificate(QualificationsCertificate instance);
    partial void InsertSquadronLog(SquadronLog instance);
    partial void UpdateSquadronLog(SquadronLog instance);
    partial void DeleteSquadronLog(SquadronLog instance);
    partial void InsertStaticImage(StaticImage instance);
    partial void UpdateStaticImage(StaticImage instance);
    partial void DeleteStaticImage(StaticImage instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public NewDatabase(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewDatabase(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewDatabase(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewDatabase(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Certificate> Certificates
		{
			get
			{
				return this.GetTable<Certificate>();
			}
		}
		
		public System.Data.Linq.Table<MissionLog> MissionLogs
		{
			get
			{
				return this.GetTable<MissionLog>();
			}
		}
		
		public System.Data.Linq.Table<Mission> Missions
		{
			get
			{
				return this.GetTable<Mission>();
			}
		}
		
		public System.Data.Linq.Table<Page> Pages
		{
			get
			{
				return this.GetTable<Page>();
			}
		}
		
		public System.Data.Linq.Table<PageStaticImage> PageStaticImages
		{
			get
			{
				return this.GetTable<PageStaticImage>();
			}
		}
		
		public System.Data.Linq.Table<Person> Persons
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
		
		public System.Data.Linq.Table<Position> Positions
		{
			get
			{
				return this.GetTable<Position>();
			}
		}
		
		public System.Data.Linq.Table<Qualification> Qualifications
		{
			get
			{
				return this.GetTable<Qualification>();
			}
		}
		
		public System.Data.Linq.Table<QualificationsCertificate> QualificationsCertificates
		{
			get
			{
				return this.GetTable<QualificationsCertificate>();
			}
		}
		
		public System.Data.Linq.Table<Schema_info> Schema_infos
		{
			get
			{
				return this.GetTable<Schema_info>();
			}
		}
		
		public System.Data.Linq.Table<SquadronLog> SquadronLogs
		{
			get
			{
				return this.GetTable<SquadronLog>();
			}
		}
		
		public System.Data.Linq.Table<StaticImage> StaticImages
		{
			get
			{
				return this.GetTable<StaticImage>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[Table(Name="dbo.Certificates")]
	public partial class Certificate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Type;
		
		private string _Name;
		
		private EntitySet<QualificationsCertificate> _QualificationsCertificates;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Certificate()
		{
			this._QualificationsCertificates = new EntitySet<QualificationsCertificate>(new Action<QualificationsCertificate>(this.attach_QualificationsCertificates), new Action<QualificationsCertificate>(this.detach_QualificationsCertificates));
			OnCreated();
		}
		
		[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Association(Name="FK_QualificationsCertificates_Certificates", Storage="_QualificationsCertificates", ThisKey="Id", OtherKey="CertificateId", DeleteRule="NO ACTION")]
		public EntitySet<QualificationsCertificate> QualificationsCertificates
		{
			get
			{
				return this._QualificationsCertificates;
			}
			set
			{
				this._QualificationsCertificates.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QualificationsCertificates(QualificationsCertificate entity)
		{
			this.SendPropertyChanging();
			entity.Certificate = this;
		}
		
		private void detach_QualificationsCertificates(QualificationsCertificate entity)
		{
			this.SendPropertyChanging();
			entity.Certificate = null;
		}
	}
	
	[Table(Name="dbo.MissionLogs")]
	public partial class MissionLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _LogDate;
		
		private System.DateTime _LastModifiedDate;
		
		private string _Location;
		
		private string _AircraftMDS;
		
		private string _AircraftSerialNumber;
		
		private EntitySet<Mission> _Missions;
		
		private EntitySet<SquadronLog> _SquadronLogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLogDateChanging(System.DateTime value);
    partial void OnLogDateChanged();
    partial void OnLastModifiedDateChanging(System.DateTime value);
    partial void OnLastModifiedDateChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnAircraftMDSChanging(string value);
    partial void OnAircraftMDSChanged();
    partial void OnAircraftSerialNumberChanging(string value);
    partial void OnAircraftSerialNumberChanged();
    #endregion
		
		public MissionLog()
		{
			this._Missions = new EntitySet<Mission>(new Action<Mission>(this.attach_Missions), new Action<Mission>(this.detach_Missions));
			this._SquadronLogs = new EntitySet<SquadronLog>(new Action<SquadronLog>(this.attach_SquadronLogs), new Action<SquadronLog>(this.detach_SquadronLogs));
			OnCreated();
		}
		
		[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_LogDate", DbType="DateTime2(7) NOT NULL")]
		public System.DateTime LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this.OnLogDateChanging(value);
					this.SendPropertyChanging();
					this._LogDate = value;
					this.SendPropertyChanged("LogDate");
					this.OnLogDateChanged();
				}
			}
		}
		
		[Column(Storage="_LastModifiedDate", DbType="DateTime2(7) NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this.OnLastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedDate = value;
					this.SendPropertyChanged("LastModifiedDate");
					this.OnLastModifiedDateChanged();
				}
			}
		}
		
		[Column(Storage="_Location", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[Column(Storage="_AircraftMDS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AircraftMDS
		{
			get
			{
				return this._AircraftMDS;
			}
			set
			{
				if ((this._AircraftMDS != value))
				{
					this.OnAircraftMDSChanging(value);
					this.SendPropertyChanging();
					this._AircraftMDS = value;
					this.SendPropertyChanged("AircraftMDS");
					this.OnAircraftMDSChanged();
				}
			}
		}
		
		[Column(Storage="_AircraftSerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AircraftSerialNumber
		{
			get
			{
				return this._AircraftSerialNumber;
			}
			set
			{
				if ((this._AircraftSerialNumber != value))
				{
					this.OnAircraftSerialNumberChanging(value);
					this.SendPropertyChanging();
					this._AircraftSerialNumber = value;
					this.SendPropertyChanged("AircraftSerialNumber");
					this.OnAircraftSerialNumberChanged();
				}
			}
		}
		
		[Association(Name="FK_Missions_MissionLogs", Storage="_Missions", ThisKey="Id", OtherKey="MissionLogId", DeleteRule="NO ACTION")]
		public EntitySet<Mission> Missions
		{
			get
			{
				return this._Missions;
			}
			set
			{
				this._Missions.Assign(value);
			}
		}
		
		[Association(Name="FK_SquadronLogs_MissionLogs", Storage="_SquadronLogs", ThisKey="Id", OtherKey="MissionLogId", DeleteRule="NO ACTION")]
		public EntitySet<SquadronLog> SquadronLogs
		{
			get
			{
				return this._SquadronLogs;
			}
			set
			{
				this._SquadronLogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Missions(Mission entity)
		{
			this.SendPropertyChanging();
			entity.MissionLog = this;
		}
		
		private void detach_Missions(Mission entity)
		{
			this.SendPropertyChanging();
			entity.MissionLog = null;
		}
		
		private void attach_SquadronLogs(SquadronLog entity)
		{
			this.SendPropertyChanging();
			entity.MissionLog = this;
		}
		
		private void detach_SquadronLogs(SquadronLog entity)
		{
			this.SendPropertyChanging();
			entity.MissionLog = null;
		}
	}
	
	[Table(Name="dbo.Missions")]
	public partial class Mission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _AdditionalInfo;
		
		private string _FromICAO;
		
		private string _ToICAO;
		
		private string _TakeOffTime;
		
		private string _LandingTime;
		
		private int _TouchAndGos;
		
		private int _FullStops;
		
		private int _Sorties;
		
		private int _Totals;
		
		private int _MissionLogId;
		
		private EntityRef<MissionLog> _MissionLog;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAdditionalInfoChanging(string value);
    partial void OnAdditionalInfoChanged();
    partial void OnFromICAOChanging(string value);
    partial void OnFromICAOChanged();
    partial void OnToICAOChanging(string value);
    partial void OnToICAOChanged();
    partial void OnTakeOffTimeChanging(string value);
    partial void OnTakeOffTimeChanged();
    partial void OnLandingTimeChanging(string value);
    partial void OnLandingTimeChanged();
    partial void OnTouchAndGosChanging(int value);
    partial void OnTouchAndGosChanged();
    partial void OnFullStopsChanging(int value);
    partial void OnFullStopsChanged();
    partial void OnSortiesChanging(int value);
    partial void OnSortiesChanged();
    partial void OnTotalsChanging(int value);
    partial void OnTotalsChanged();
    partial void OnMissionLogIdChanging(int value);
    partial void OnMissionLogIdChanged();
    #endregion
		
		public Mission()
		{
			this._MissionLog = default(EntityRef<MissionLog>);
			OnCreated();
		}
		
		[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_AdditionalInfo", DbType="NVarChar(100)")]
		public string AdditionalInfo
		{
			get
			{
				return this._AdditionalInfo;
			}
			set
			{
				if ((this._AdditionalInfo != value))
				{
					this.OnAdditionalInfoChanging(value);
					this.SendPropertyChanging();
					this._AdditionalInfo = value;
					this.SendPropertyChanged("AdditionalInfo");
					this.OnAdditionalInfoChanged();
				}
			}
		}
		
		[Column(Storage="_FromICAO", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string FromICAO
		{
			get
			{
				return this._FromICAO;
			}
			set
			{
				if ((this._FromICAO != value))
				{
					this.OnFromICAOChanging(value);
					this.SendPropertyChanging();
					this._FromICAO = value;
					this.SendPropertyChanged("FromICAO");
					this.OnFromICAOChanged();
				}
			}
		}
		
		[Column(Storage="_ToICAO", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string ToICAO
		{
			get
			{
				return this._ToICAO;
			}
			set
			{
				if ((this._ToICAO != value))
				{
					this.OnToICAOChanging(value);
					this.SendPropertyChanging();
					this._ToICAO = value;
					this.SendPropertyChanged("ToICAO");
					this.OnToICAOChanged();
				}
			}
		}
		
		[Column(Storage="_TakeOffTime", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string TakeOffTime
		{
			get
			{
				return this._TakeOffTime;
			}
			set
			{
				if ((this._TakeOffTime != value))
				{
					this.OnTakeOffTimeChanging(value);
					this.SendPropertyChanging();
					this._TakeOffTime = value;
					this.SendPropertyChanged("TakeOffTime");
					this.OnTakeOffTimeChanged();
				}
			}
		}
		
		[Column(Storage="_LandingTime", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string LandingTime
		{
			get
			{
				return this._LandingTime;
			}
			set
			{
				if ((this._LandingTime != value))
				{
					this.OnLandingTimeChanging(value);
					this.SendPropertyChanging();
					this._LandingTime = value;
					this.SendPropertyChanged("LandingTime");
					this.OnLandingTimeChanged();
				}
			}
		}
		
		[Column(Storage="_TouchAndGos", DbType="Int NOT NULL")]
		public int TouchAndGos
		{
			get
			{
				return this._TouchAndGos;
			}
			set
			{
				if ((this._TouchAndGos != value))
				{
					this.OnTouchAndGosChanging(value);
					this.SendPropertyChanging();
					this._TouchAndGos = value;
					this.SendPropertyChanged("TouchAndGos");
					this.OnTouchAndGosChanged();
				}
			}
		}
		
		[Column(Storage="_FullStops", DbType="Int NOT NULL")]
		public int FullStops
		{
			get
			{
				return this._FullStops;
			}
			set
			{
				if ((this._FullStops != value))
				{
					this.OnFullStopsChanging(value);
					this.SendPropertyChanging();
					this._FullStops = value;
					this.SendPropertyChanged("FullStops");
					this.OnFullStopsChanged();
				}
			}
		}
		
		[Column(Storage="_Sorties", DbType="Int NOT NULL")]
		public int Sorties
		{
			get
			{
				return this._Sorties;
			}
			set
			{
				if ((this._Sorties != value))
				{
					this.OnSortiesChanging(value);
					this.SendPropertyChanging();
					this._Sorties = value;
					this.SendPropertyChanged("Sorties");
					this.OnSortiesChanged();
				}
			}
		}
		
		[Column(Storage="_Totals", DbType="Int NOT NULL")]
		public int Totals
		{
			get
			{
				return this._Totals;
			}
			set
			{
				if ((this._Totals != value))
				{
					this.OnTotalsChanging(value);
					this.SendPropertyChanging();
					this._Totals = value;
					this.SendPropertyChanged("Totals");
					this.OnTotalsChanged();
				}
			}
		}
		
		[Column(Storage="_MissionLogId", DbType="Int NOT NULL")]
		public int MissionLogId
		{
			get
			{
				return this._MissionLogId;
			}
			set
			{
				if ((this._MissionLogId != value))
				{
					if (this._MissionLog.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMissionLogIdChanging(value);
					this.SendPropertyChanging();
					this._MissionLogId = value;
					this.SendPropertyChanged("MissionLogId");
					this.OnMissionLogIdChanged();
				}
			}
		}
		
		[Association(Name="FK_Missions_MissionLogs", Storage="_MissionLog", ThisKey="MissionLogId", OtherKey="Id", IsForeignKey=true)]
		public MissionLog MissionLog
		{
			get
			{
				return this._MissionLog.Entity;
			}
			set
			{
				MissionLog previousValue = this._MissionLog.Entity;
				if (((previousValue != value) 
							|| (this._MissionLog.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MissionLog.Entity = null;
						previousValue.Missions.Remove(this);
					}
					this._MissionLog.Entity = value;
					if ((value != null))
					{
						value.Missions.Add(this);
						this._MissionLogId = value.Id;
					}
					else
					{
						this._MissionLogId = default(int);
					}
					this.SendPropertyChanged("MissionLog");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Pages")]
	public partial class Page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _URI;
		
		private string _Title;
		
		private string _Content;
		
		private string _BannerFileName;
		
		private string _HeaderFileName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnURIChanging(string value);
    partial void OnURIChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnBannerFileNameChanging(string value);
    partial void OnBannerFileNameChanged();
    partial void OnHeaderFileNameChanging(string value);
    partial void OnHeaderFileNameChanged();
    #endregion
		
		public Page()
		{
			OnCreated();
		}
		
		[Column(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_URI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string URI
		{
			get
			{
				return this._URI;
			}
			set
			{
				if ((this._URI != value))
				{
					this.OnURIChanging(value);
					this.SendPropertyChanging();
					this._URI = value;
					this.SendPropertyChanged("URI");
					this.OnURIChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[Column(Storage="_BannerFileName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BannerFileName
		{
			get
			{
				return this._BannerFileName;
			}
			set
			{
				if ((this._BannerFileName != value))
				{
					this.OnBannerFileNameChanging(value);
					this.SendPropertyChanging();
					this._BannerFileName = value;
					this.SendPropertyChanged("BannerFileName");
					this.OnBannerFileNameChanged();
				}
			}
		}
		
		[Column(Storage="_HeaderFileName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HeaderFileName
		{
			get
			{
				return this._HeaderFileName;
			}
			set
			{
				if ((this._HeaderFileName != value))
				{
					this.OnHeaderFileNameChanging(value);
					this.SendPropertyChanging();
					this._HeaderFileName = value;
					this.SendPropertyChanged("HeaderFileName");
					this.OnHeaderFileNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.PageStaticImages")]
	public partial class PageStaticImage
	{
		
		private System.Guid _PageId;
		
		private System.Guid _StaticImageId;
		
		public PageStaticImage()
		{
		}
		
		[Column(Storage="_PageId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid PageId
		{
			get
			{
				return this._PageId;
			}
			set
			{
				if ((this._PageId != value))
				{
					this._PageId = value;
				}
			}
		}
		
		[Column(Storage="_StaticImageId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StaticImageId
		{
			get
			{
				return this._StaticImageId;
			}
			set
			{
				if ((this._StaticImageId != value))
				{
					this._StaticImageId = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Persons")]
	public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonId;
		
		private string _StreetAddress;
		
		private string _City;
		
		private string _State;
		
		private string _ZipCode;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _MiddleInitial;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private System.Nullable<int> _Gender;
		
		private string _SocialSecurityLastFour;
		
		private string _PrimaryPhoneNumber;
		
		private string _AlternatePhoneNumber;
		
		private string _EmergencyContactName;
		
		private string _EmergencyContactPhoneNumber;
		
		private System.Nullable<int> _ShirtSize;
		
		private System.Nullable<int> _FlightSuitSize;
		
		private System.Nullable<int> _HirePositionId;
		
		private string _AlternateEmail;
		
		private EntityRef<Position> _Position;
		
		private EntityRef<User> _User;
		
		private EntityRef<Qualification> _Qualification;
		
		private EntitySet<SquadronLog> _SquadronLogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonIdChanging(int value);
    partial void OnPersonIdChanged();
    partial void OnStreetAddressChanging(string value);
    partial void OnStreetAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleInitialChanging(string value);
    partial void OnMiddleInitialChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnGenderChanging(System.Nullable<int> value);
    partial void OnGenderChanged();
    partial void OnSocialSecurityLastFourChanging(string value);
    partial void OnSocialSecurityLastFourChanged();
    partial void OnPrimaryPhoneNumberChanging(string value);
    partial void OnPrimaryPhoneNumberChanged();
    partial void OnAlternatePhoneNumberChanging(string value);
    partial void OnAlternatePhoneNumberChanged();
    partial void OnEmergencyContactNameChanging(string value);
    partial void OnEmergencyContactNameChanged();
    partial void OnEmergencyContactPhoneNumberChanging(string value);
    partial void OnEmergencyContactPhoneNumberChanged();
    partial void OnShirtSizeChanging(System.Nullable<int> value);
    partial void OnShirtSizeChanged();
    partial void OnFlightSuitSizeChanging(System.Nullable<int> value);
    partial void OnFlightSuitSizeChanged();
    partial void OnHirePositionIdChanging(System.Nullable<int> value);
    partial void OnHirePositionIdChanged();
    partial void OnAlternateEmailChanging(string value);
    partial void OnAlternateEmailChanged();
    #endregion
		
		public Person()
		{
			this._Position = default(EntityRef<Position>);
			this._User = default(EntityRef<User>);
			this._Qualification = default(EntityRef<Qualification>);
			this._SquadronLogs = new EntitySet<SquadronLog>(new Action<SquadronLog>(this.attach_SquadronLogs), new Action<SquadronLog>(this.detach_SquadronLogs));
			OnCreated();
		}
		
		[Column(Storage="_PersonId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PersonId
		{
			get
			{
				return this._PersonId;
			}
			set
			{
				if ((this._PersonId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonIdChanging(value);
					this.SendPropertyChanging();
					this._PersonId = value;
					this.SendPropertyChanged("PersonId");
					this.OnPersonIdChanged();
				}
			}
		}
		
		[Column(Storage="_StreetAddress", DbType="NVarChar(100)")]
		public string StreetAddress
		{
			get
			{
				return this._StreetAddress;
			}
			set
			{
				if ((this._StreetAddress != value))
				{
					this.OnStreetAddressChanging(value);
					this.SendPropertyChanging();
					this._StreetAddress = value;
					this.SendPropertyChanged("StreetAddress");
					this.OnStreetAddressChanged();
				}
			}
		}
		
		[Column(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[Column(Storage="_State", DbType="NVarChar(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[Column(Storage="_ZipCode", DbType="NVarChar(5)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[Column(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[Column(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[Column(Storage="_MiddleInitial", DbType="NVarChar(50)")]
		public string MiddleInitial
		{
			get
			{
				return this._MiddleInitial;
			}
			set
			{
				if ((this._MiddleInitial != value))
				{
					this.OnMiddleInitialChanging(value);
					this.SendPropertyChanging();
					this._MiddleInitial = value;
					this.SendPropertyChanged("MiddleInitial");
					this.OnMiddleInitialChanged();
				}
			}
		}
		
		[Column(Storage="_DateOfBirth", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[Column(Storage="_Gender", DbType="Int")]
		public System.Nullable<int> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[Column(Storage="_SocialSecurityLastFour", DbType="NVarChar(4)")]
		public string SocialSecurityLastFour
		{
			get
			{
				return this._SocialSecurityLastFour;
			}
			set
			{
				if ((this._SocialSecurityLastFour != value))
				{
					this.OnSocialSecurityLastFourChanging(value);
					this.SendPropertyChanging();
					this._SocialSecurityLastFour = value;
					this.SendPropertyChanged("SocialSecurityLastFour");
					this.OnSocialSecurityLastFourChanged();
				}
			}
		}
		
		[Column(Storage="_PrimaryPhoneNumber", DbType="NVarChar(10)")]
		public string PrimaryPhoneNumber
		{
			get
			{
				return this._PrimaryPhoneNumber;
			}
			set
			{
				if ((this._PrimaryPhoneNumber != value))
				{
					this.OnPrimaryPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PrimaryPhoneNumber = value;
					this.SendPropertyChanged("PrimaryPhoneNumber");
					this.OnPrimaryPhoneNumberChanged();
				}
			}
		}
		
		[Column(Storage="_AlternatePhoneNumber", DbType="NVarChar(10)")]
		public string AlternatePhoneNumber
		{
			get
			{
				return this._AlternatePhoneNumber;
			}
			set
			{
				if ((this._AlternatePhoneNumber != value))
				{
					this.OnAlternatePhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._AlternatePhoneNumber = value;
					this.SendPropertyChanged("AlternatePhoneNumber");
					this.OnAlternatePhoneNumberChanged();
				}
			}
		}
		
		[Column(Storage="_EmergencyContactName", DbType="NVarChar(50)")]
		public string EmergencyContactName
		{
			get
			{
				return this._EmergencyContactName;
			}
			set
			{
				if ((this._EmergencyContactName != value))
				{
					this.OnEmergencyContactNameChanging(value);
					this.SendPropertyChanging();
					this._EmergencyContactName = value;
					this.SendPropertyChanged("EmergencyContactName");
					this.OnEmergencyContactNameChanged();
				}
			}
		}
		
		[Column(Storage="_EmergencyContactPhoneNumber", DbType="NVarChar(50)")]
		public string EmergencyContactPhoneNumber
		{
			get
			{
				return this._EmergencyContactPhoneNumber;
			}
			set
			{
				if ((this._EmergencyContactPhoneNumber != value))
				{
					this.OnEmergencyContactPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._EmergencyContactPhoneNumber = value;
					this.SendPropertyChanged("EmergencyContactPhoneNumber");
					this.OnEmergencyContactPhoneNumberChanged();
				}
			}
		}
		
		[Column(Storage="_ShirtSize", DbType="Int")]
		public System.Nullable<int> ShirtSize
		{
			get
			{
				return this._ShirtSize;
			}
			set
			{
				if ((this._ShirtSize != value))
				{
					this.OnShirtSizeChanging(value);
					this.SendPropertyChanging();
					this._ShirtSize = value;
					this.SendPropertyChanged("ShirtSize");
					this.OnShirtSizeChanged();
				}
			}
		}
		
		[Column(Storage="_FlightSuitSize", DbType="Int")]
		public System.Nullable<int> FlightSuitSize
		{
			get
			{
				return this._FlightSuitSize;
			}
			set
			{
				if ((this._FlightSuitSize != value))
				{
					this.OnFlightSuitSizeChanging(value);
					this.SendPropertyChanging();
					this._FlightSuitSize = value;
					this.SendPropertyChanged("FlightSuitSize");
					this.OnFlightSuitSizeChanged();
				}
			}
		}
		
		[Column(Storage="_HirePositionId", DbType="Int")]
		public System.Nullable<int> HirePositionId
		{
			get
			{
				return this._HirePositionId;
			}
			set
			{
				if ((this._HirePositionId != value))
				{
					if (this._Position.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHirePositionIdChanging(value);
					this.SendPropertyChanging();
					this._HirePositionId = value;
					this.SendPropertyChanged("HirePositionId");
					this.OnHirePositionIdChanged();
				}
			}
		}
		
		[Column(Storage="_AlternateEmail", DbType="NVarChar(254)")]
		public string AlternateEmail
		{
			get
			{
				return this._AlternateEmail;
			}
			set
			{
				if ((this._AlternateEmail != value))
				{
					this.OnAlternateEmailChanging(value);
					this.SendPropertyChanging();
					this._AlternateEmail = value;
					this.SendPropertyChanged("AlternateEmail");
					this.OnAlternateEmailChanged();
				}
			}
		}
		
		[Association(Name="FK_Persons_Positions", Storage="_Position", ThisKey="HirePositionId", OtherKey="Id", IsForeignKey=true)]
		public Position Position
		{
			get
			{
				return this._Position.Entity;
			}
			set
			{
				Position previousValue = this._Position.Entity;
				if (((previousValue != value) 
							|| (this._Position.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Position.Entity = null;
						previousValue.Persons.Remove(this);
					}
					this._Position.Entity = value;
					if ((value != null))
					{
						value.Persons.Add(this);
						this._HirePositionId = value.Id;
					}
					else
					{
						this._HirePositionId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Position");
				}
			}
		}
		
		[Association(Name="FK_Persons_Users", Storage="_User", ThisKey="PersonId", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Person = null;
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Person = this;
						this._PersonId = value.Id;
					}
					else
					{
						this._PersonId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[Association(Name="FK_Qualifications_Person", Storage="_Qualification", ThisKey="PersonId", OtherKey="PersonId", IsUnique=true, IsForeignKey=false, DeleteRule="NO ACTION")]
		public Qualification Qualification
		{
			get
			{
				return this._Qualification.Entity;
			}
			set
			{
				Qualification previousValue = this._Qualification.Entity;
				if (((previousValue != value) 
							|| (this._Qualification.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Qualification.Entity = null;
						previousValue.Person = null;
					}
					this._Qualification.Entity = value;
					if ((value != null))
					{
						value.Person = this;
					}
					this.SendPropertyChanged("Qualification");
				}
			}
		}
		
		[Association(Name="FK_SquadronLogs_Persons", Storage="_SquadronLogs", ThisKey="PersonId", OtherKey="PersonId", DeleteRule="NO ACTION")]
		public EntitySet<SquadronLog> SquadronLogs
		{
			get
			{
				return this._SquadronLogs;
			}
			set
			{
				this._SquadronLogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SquadronLogs(SquadronLog entity)
		{
			this.SendPropertyChanging();
			entity.Person = this;
		}
		
		private void detach_SquadronLogs(SquadronLog entity)
		{
			this.SendPropertyChanging();
			entity.Person = null;
		}
	}
	
	[Table(Name="dbo.Positions")]
	public partial class Position : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Title;
		
		private EntitySet<Person> _Persons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public Position()
		{
			this._Persons = new EntitySet<Person>(new Action<Person>(this.attach_Persons), new Action<Person>(this.detach_Persons));
			OnCreated();
		}
		
		[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Association(Name="FK_Persons_Positions", Storage="_Persons", ThisKey="Id", OtherKey="HirePositionId", DeleteRule="NO ACTION")]
		public EntitySet<Person> Persons
		{
			get
			{
				return this._Persons;
			}
			set
			{
				this._Persons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Persons(Person entity)
		{
			this.SendPropertyChanging();
			entity.Position = this;
		}
		
		private void detach_Persons(Person entity)
		{
			this.SendPropertyChanging();
			entity.Position = null;
		}
	}
	
	[Table(Name="dbo.Qualifications")]
	public partial class Qualification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonId;
		
		private System.Nullable<int> _BranchOfService;
		
		private System.Nullable<int> _MilitaryFCFQualification;
		
		private System.Nullable<System.DateTime> _LastAltitudeChamber;
		
		private System.Nullable<System.DateTime> _LastBFR;
		
		private System.Nullable<System.DateTime> _LastCRM;
		
		private System.Nullable<System.DateTime> _LastEgreesTraining;
		
		private System.Nullable<System.DateTime> _LastFlight;
		
		private System.Nullable<System.DateTime> _LastLifeSupportTraining;
		
		private System.Nullable<System.DateTime> _LastMilitaryFlightPhysical;
		
		private System.Nullable<System.DateTime> _LastSimulatorRefresher;
		
		private EntityRef<Person> _Person;
		
		private EntitySet<QualificationsCertificate> _QualificationsCertificates;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonIdChanging(int value);
    partial void OnPersonIdChanged();
    partial void OnBranchOfServiceChanging(System.Nullable<int> value);
    partial void OnBranchOfServiceChanged();
    partial void OnMilitaryFCFQualificationChanging(System.Nullable<int> value);
    partial void OnMilitaryFCFQualificationChanged();
    partial void OnLastAltitudeChamberChanging(System.Nullable<System.DateTime> value);
    partial void OnLastAltitudeChamberChanged();
    partial void OnLastBFRChanging(System.Nullable<System.DateTime> value);
    partial void OnLastBFRChanged();
    partial void OnLastCRMChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCRMChanged();
    partial void OnLastEgreesTrainingChanging(System.Nullable<System.DateTime> value);
    partial void OnLastEgreesTrainingChanged();
    partial void OnLastFlightChanging(System.Nullable<System.DateTime> value);
    partial void OnLastFlightChanged();
    partial void OnLastLifeSupportTrainingChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLifeSupportTrainingChanged();
    partial void OnLastMilitaryFlightPhysicalChanging(System.Nullable<System.DateTime> value);
    partial void OnLastMilitaryFlightPhysicalChanged();
    partial void OnLastSimulatorRefresherChanging(System.Nullable<System.DateTime> value);
    partial void OnLastSimulatorRefresherChanged();
    #endregion
		
		public Qualification()
		{
			this._Person = default(EntityRef<Person>);
			this._QualificationsCertificates = new EntitySet<QualificationsCertificate>(new Action<QualificationsCertificate>(this.attach_QualificationsCertificates), new Action<QualificationsCertificate>(this.detach_QualificationsCertificates));
			OnCreated();
		}
		
		[Column(Storage="_PersonId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PersonId
		{
			get
			{
				return this._PersonId;
			}
			set
			{
				if ((this._PersonId != value))
				{
					if (this._Person.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonIdChanging(value);
					this.SendPropertyChanging();
					this._PersonId = value;
					this.SendPropertyChanged("PersonId");
					this.OnPersonIdChanged();
				}
			}
		}
		
		[Column(Storage="_BranchOfService", DbType="Int")]
		public System.Nullable<int> BranchOfService
		{
			get
			{
				return this._BranchOfService;
			}
			set
			{
				if ((this._BranchOfService != value))
				{
					this.OnBranchOfServiceChanging(value);
					this.SendPropertyChanging();
					this._BranchOfService = value;
					this.SendPropertyChanged("BranchOfService");
					this.OnBranchOfServiceChanged();
				}
			}
		}
		
		[Column(Storage="_MilitaryFCFQualification", DbType="Int")]
		public System.Nullable<int> MilitaryFCFQualification
		{
			get
			{
				return this._MilitaryFCFQualification;
			}
			set
			{
				if ((this._MilitaryFCFQualification != value))
				{
					this.OnMilitaryFCFQualificationChanging(value);
					this.SendPropertyChanging();
					this._MilitaryFCFQualification = value;
					this.SendPropertyChanged("MilitaryFCFQualification");
					this.OnMilitaryFCFQualificationChanged();
				}
			}
		}
		
		[Column(Storage="_LastAltitudeChamber", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastAltitudeChamber
		{
			get
			{
				return this._LastAltitudeChamber;
			}
			set
			{
				if ((this._LastAltitudeChamber != value))
				{
					this.OnLastAltitudeChamberChanging(value);
					this.SendPropertyChanging();
					this._LastAltitudeChamber = value;
					this.SendPropertyChanged("LastAltitudeChamber");
					this.OnLastAltitudeChamberChanged();
				}
			}
		}
		
		[Column(Storage="_LastBFR", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastBFR
		{
			get
			{
				return this._LastBFR;
			}
			set
			{
				if ((this._LastBFR != value))
				{
					this.OnLastBFRChanging(value);
					this.SendPropertyChanging();
					this._LastBFR = value;
					this.SendPropertyChanged("LastBFR");
					this.OnLastBFRChanged();
				}
			}
		}
		
		[Column(Storage="_LastCRM", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastCRM
		{
			get
			{
				return this._LastCRM;
			}
			set
			{
				if ((this._LastCRM != value))
				{
					this.OnLastCRMChanging(value);
					this.SendPropertyChanging();
					this._LastCRM = value;
					this.SendPropertyChanged("LastCRM");
					this.OnLastCRMChanged();
				}
			}
		}
		
		[Column(Storage="_LastEgreesTraining", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastEgreesTraining
		{
			get
			{
				return this._LastEgreesTraining;
			}
			set
			{
				if ((this._LastEgreesTraining != value))
				{
					this.OnLastEgreesTrainingChanging(value);
					this.SendPropertyChanging();
					this._LastEgreesTraining = value;
					this.SendPropertyChanged("LastEgreesTraining");
					this.OnLastEgreesTrainingChanged();
				}
			}
		}
		
		[Column(Storage="_LastFlight", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastFlight
		{
			get
			{
				return this._LastFlight;
			}
			set
			{
				if ((this._LastFlight != value))
				{
					this.OnLastFlightChanging(value);
					this.SendPropertyChanging();
					this._LastFlight = value;
					this.SendPropertyChanged("LastFlight");
					this.OnLastFlightChanged();
				}
			}
		}
		
		[Column(Storage="_LastLifeSupportTraining", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastLifeSupportTraining
		{
			get
			{
				return this._LastLifeSupportTraining;
			}
			set
			{
				if ((this._LastLifeSupportTraining != value))
				{
					this.OnLastLifeSupportTrainingChanging(value);
					this.SendPropertyChanging();
					this._LastLifeSupportTraining = value;
					this.SendPropertyChanged("LastLifeSupportTraining");
					this.OnLastLifeSupportTrainingChanged();
				}
			}
		}
		
		[Column(Storage="_LastMilitaryFlightPhysical", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastMilitaryFlightPhysical
		{
			get
			{
				return this._LastMilitaryFlightPhysical;
			}
			set
			{
				if ((this._LastMilitaryFlightPhysical != value))
				{
					this.OnLastMilitaryFlightPhysicalChanging(value);
					this.SendPropertyChanging();
					this._LastMilitaryFlightPhysical = value;
					this.SendPropertyChanged("LastMilitaryFlightPhysical");
					this.OnLastMilitaryFlightPhysicalChanged();
				}
			}
		}
		
		[Column(Storage="_LastSimulatorRefresher", DbType="DateTime2(7)")]
		public System.Nullable<System.DateTime> LastSimulatorRefresher
		{
			get
			{
				return this._LastSimulatorRefresher;
			}
			set
			{
				if ((this._LastSimulatorRefresher != value))
				{
					this.OnLastSimulatorRefresherChanging(value);
					this.SendPropertyChanging();
					this._LastSimulatorRefresher = value;
					this.SendPropertyChanged("LastSimulatorRefresher");
					this.OnLastSimulatorRefresherChanged();
				}
			}
		}
		
		[Association(Name="FK_Qualifications_Person", Storage="_Person", ThisKey="PersonId", OtherKey="PersonId", IsForeignKey=true)]
		public Person Person
		{
			get
			{
				return this._Person.Entity;
			}
			set
			{
				Person previousValue = this._Person.Entity;
				if (((previousValue != value) 
							|| (this._Person.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Person.Entity = null;
						previousValue.Qualification = null;
					}
					this._Person.Entity = value;
					if ((value != null))
					{
						value.Qualification = this;
						this._PersonId = value.PersonId;
					}
					else
					{
						this._PersonId = default(int);
					}
					this.SendPropertyChanged("Person");
				}
			}
		}
		
		[Association(Name="FK_QualificationsCertificates_Qualifications", Storage="_QualificationsCertificates", ThisKey="PersonId", OtherKey="PersonId", DeleteRule="NO ACTION")]
		public EntitySet<QualificationsCertificate> QualificationsCertificates
		{
			get
			{
				return this._QualificationsCertificates;
			}
			set
			{
				this._QualificationsCertificates.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QualificationsCertificates(QualificationsCertificate entity)
		{
			this.SendPropertyChanging();
			entity.Qualification = this;
		}
		
		private void detach_QualificationsCertificates(QualificationsCertificate entity)
		{
			this.SendPropertyChanging();
			entity.Qualification = null;
		}
	}
	
	[Table(Name="dbo.QualificationsCertificates")]
	public partial class QualificationsCertificate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonId;
		
		private int _CertificateId;
		
		private EntityRef<Certificate> _Certificate;
		
		private EntityRef<Qualification> _Qualification;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonIdChanging(int value);
    partial void OnPersonIdChanged();
    partial void OnCertificateIdChanging(int value);
    partial void OnCertificateIdChanged();
    #endregion
		
		public QualificationsCertificate()
		{
			this._Certificate = default(EntityRef<Certificate>);
			this._Qualification = default(EntityRef<Qualification>);
			OnCreated();
		}
		
		[Column(Storage="_PersonId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PersonId
		{
			get
			{
				return this._PersonId;
			}
			set
			{
				if ((this._PersonId != value))
				{
					if (this._Qualification.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonIdChanging(value);
					this.SendPropertyChanging();
					this._PersonId = value;
					this.SendPropertyChanged("PersonId");
					this.OnPersonIdChanged();
				}
			}
		}
		
		[Column(Storage="_CertificateId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CertificateId
		{
			get
			{
				return this._CertificateId;
			}
			set
			{
				if ((this._CertificateId != value))
				{
					if (this._Certificate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCertificateIdChanging(value);
					this.SendPropertyChanging();
					this._CertificateId = value;
					this.SendPropertyChanged("CertificateId");
					this.OnCertificateIdChanged();
				}
			}
		}
		
		[Association(Name="FK_QualificationsCertificates_Certificates", Storage="_Certificate", ThisKey="CertificateId", OtherKey="Id", IsForeignKey=true)]
		public Certificate Certificate
		{
			get
			{
				return this._Certificate.Entity;
			}
			set
			{
				Certificate previousValue = this._Certificate.Entity;
				if (((previousValue != value) 
							|| (this._Certificate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Certificate.Entity = null;
						previousValue.QualificationsCertificates.Remove(this);
					}
					this._Certificate.Entity = value;
					if ((value != null))
					{
						value.QualificationsCertificates.Add(this);
						this._CertificateId = value.Id;
					}
					else
					{
						this._CertificateId = default(int);
					}
					this.SendPropertyChanged("Certificate");
				}
			}
		}
		
		[Association(Name="FK_QualificationsCertificates_Qualifications", Storage="_Qualification", ThisKey="PersonId", OtherKey="PersonId", IsForeignKey=true)]
		public Qualification Qualification
		{
			get
			{
				return this._Qualification.Entity;
			}
			set
			{
				Qualification previousValue = this._Qualification.Entity;
				if (((previousValue != value) 
							|| (this._Qualification.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Qualification.Entity = null;
						previousValue.QualificationsCertificates.Remove(this);
					}
					this._Qualification.Entity = value;
					if ((value != null))
					{
						value.QualificationsCertificates.Add(this);
						this._PersonId = value.PersonId;
					}
					else
					{
						this._PersonId = default(int);
					}
					this.SendPropertyChanged("Qualification");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.schema_info")]
	public partial class Schema_info
	{
		
		private int _Version;
		
		private string _Migration_script;
		
		public Schema_info()
		{
		}
		
		[Column(Name="version", Storage="_Version", DbType="Int NOT NULL")]
		public int Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[Column(Name="migration_script", Storage="_Migration_script", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Migration_script
		{
			get
			{
				return this._Migration_script;
			}
			set
			{
				if ((this._Migration_script != value))
				{
					this._Migration_script = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.SquadronLogs")]
	public partial class SquadronLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _DutyCode;
		
		private double _PrimaryHours;
		
		private double _SecondaryHours;
		
		private double _InstructorHours;
		
		private double _EvaluatorHours;
		
		private double _OtherHours;
		
		private int _Sorties;
		
		private double _PrimaryNightHours;
		
		private double _PrimaryInstrumentHours;
		
		private double _SimulatedInstrumentHours;
		
		private int _MissionLogId;
		
		private int _PersonId;
		
		private EntityRef<MissionLog> _MissionLog;
		
		private EntityRef<Person> _Person;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDutyCodeChanging(int value);
    partial void OnDutyCodeChanged();
    partial void OnPrimaryHoursChanging(double value);
    partial void OnPrimaryHoursChanged();
    partial void OnSecondaryHoursChanging(double value);
    partial void OnSecondaryHoursChanged();
    partial void OnInstructorHoursChanging(double value);
    partial void OnInstructorHoursChanged();
    partial void OnEvaluatorHoursChanging(double value);
    partial void OnEvaluatorHoursChanged();
    partial void OnOtherHoursChanging(double value);
    partial void OnOtherHoursChanged();
    partial void OnSortiesChanging(int value);
    partial void OnSortiesChanged();
    partial void OnPrimaryNightHoursChanging(double value);
    partial void OnPrimaryNightHoursChanged();
    partial void OnPrimaryInstrumentHoursChanging(double value);
    partial void OnPrimaryInstrumentHoursChanged();
    partial void OnSimulatedInstrumentHoursChanging(double value);
    partial void OnSimulatedInstrumentHoursChanged();
    partial void OnMissionLogIdChanging(int value);
    partial void OnMissionLogIdChanged();
    partial void OnPersonIdChanging(int value);
    partial void OnPersonIdChanged();
    #endregion
		
		public SquadronLog()
		{
			this._MissionLog = default(EntityRef<MissionLog>);
			this._Person = default(EntityRef<Person>);
			OnCreated();
		}
		
		[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_DutyCode", DbType="Int NOT NULL")]
		public int DutyCode
		{
			get
			{
				return this._DutyCode;
			}
			set
			{
				if ((this._DutyCode != value))
				{
					this.OnDutyCodeChanging(value);
					this.SendPropertyChanging();
					this._DutyCode = value;
					this.SendPropertyChanged("DutyCode");
					this.OnDutyCodeChanged();
				}
			}
		}
		
		[Column(Storage="_PrimaryHours", DbType="Float NOT NULL")]
		public double PrimaryHours
		{
			get
			{
				return this._PrimaryHours;
			}
			set
			{
				if ((this._PrimaryHours != value))
				{
					this.OnPrimaryHoursChanging(value);
					this.SendPropertyChanging();
					this._PrimaryHours = value;
					this.SendPropertyChanged("PrimaryHours");
					this.OnPrimaryHoursChanged();
				}
			}
		}
		
		[Column(Storage="_SecondaryHours", DbType="Float NOT NULL")]
		public double SecondaryHours
		{
			get
			{
				return this._SecondaryHours;
			}
			set
			{
				if ((this._SecondaryHours != value))
				{
					this.OnSecondaryHoursChanging(value);
					this.SendPropertyChanging();
					this._SecondaryHours = value;
					this.SendPropertyChanged("SecondaryHours");
					this.OnSecondaryHoursChanged();
				}
			}
		}
		
		[Column(Storage="_InstructorHours", DbType="Float NOT NULL")]
		public double InstructorHours
		{
			get
			{
				return this._InstructorHours;
			}
			set
			{
				if ((this._InstructorHours != value))
				{
					this.OnInstructorHoursChanging(value);
					this.SendPropertyChanging();
					this._InstructorHours = value;
					this.SendPropertyChanged("InstructorHours");
					this.OnInstructorHoursChanged();
				}
			}
		}
		
		[Column(Storage="_EvaluatorHours", DbType="Float NOT NULL")]
		public double EvaluatorHours
		{
			get
			{
				return this._EvaluatorHours;
			}
			set
			{
				if ((this._EvaluatorHours != value))
				{
					this.OnEvaluatorHoursChanging(value);
					this.SendPropertyChanging();
					this._EvaluatorHours = value;
					this.SendPropertyChanged("EvaluatorHours");
					this.OnEvaluatorHoursChanged();
				}
			}
		}
		
		[Column(Storage="_OtherHours", DbType="Float NOT NULL")]
		public double OtherHours
		{
			get
			{
				return this._OtherHours;
			}
			set
			{
				if ((this._OtherHours != value))
				{
					this.OnOtherHoursChanging(value);
					this.SendPropertyChanging();
					this._OtherHours = value;
					this.SendPropertyChanged("OtherHours");
					this.OnOtherHoursChanged();
				}
			}
		}
		
		[Column(Storage="_Sorties", DbType="Int NOT NULL")]
		public int Sorties
		{
			get
			{
				return this._Sorties;
			}
			set
			{
				if ((this._Sorties != value))
				{
					this.OnSortiesChanging(value);
					this.SendPropertyChanging();
					this._Sorties = value;
					this.SendPropertyChanged("Sorties");
					this.OnSortiesChanged();
				}
			}
		}
		
		[Column(Storage="_PrimaryNightHours", DbType="Float NOT NULL")]
		public double PrimaryNightHours
		{
			get
			{
				return this._PrimaryNightHours;
			}
			set
			{
				if ((this._PrimaryNightHours != value))
				{
					this.OnPrimaryNightHoursChanging(value);
					this.SendPropertyChanging();
					this._PrimaryNightHours = value;
					this.SendPropertyChanged("PrimaryNightHours");
					this.OnPrimaryNightHoursChanged();
				}
			}
		}
		
		[Column(Storage="_PrimaryInstrumentHours", DbType="Float NOT NULL")]
		public double PrimaryInstrumentHours
		{
			get
			{
				return this._PrimaryInstrumentHours;
			}
			set
			{
				if ((this._PrimaryInstrumentHours != value))
				{
					this.OnPrimaryInstrumentHoursChanging(value);
					this.SendPropertyChanging();
					this._PrimaryInstrumentHours = value;
					this.SendPropertyChanged("PrimaryInstrumentHours");
					this.OnPrimaryInstrumentHoursChanged();
				}
			}
		}
		
		[Column(Storage="_SimulatedInstrumentHours", DbType="Float NOT NULL")]
		public double SimulatedInstrumentHours
		{
			get
			{
				return this._SimulatedInstrumentHours;
			}
			set
			{
				if ((this._SimulatedInstrumentHours != value))
				{
					this.OnSimulatedInstrumentHoursChanging(value);
					this.SendPropertyChanging();
					this._SimulatedInstrumentHours = value;
					this.SendPropertyChanged("SimulatedInstrumentHours");
					this.OnSimulatedInstrumentHoursChanged();
				}
			}
		}
		
		[Column(Storage="_MissionLogId", DbType="Int NOT NULL")]
		public int MissionLogId
		{
			get
			{
				return this._MissionLogId;
			}
			set
			{
				if ((this._MissionLogId != value))
				{
					if (this._MissionLog.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMissionLogIdChanging(value);
					this.SendPropertyChanging();
					this._MissionLogId = value;
					this.SendPropertyChanged("MissionLogId");
					this.OnMissionLogIdChanged();
				}
			}
		}
		
		[Column(Storage="_PersonId", DbType="Int NOT NULL")]
		public int PersonId
		{
			get
			{
				return this._PersonId;
			}
			set
			{
				if ((this._PersonId != value))
				{
					if (this._Person.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonIdChanging(value);
					this.SendPropertyChanging();
					this._PersonId = value;
					this.SendPropertyChanged("PersonId");
					this.OnPersonIdChanged();
				}
			}
		}
		
		[Association(Name="FK_SquadronLogs_MissionLogs", Storage="_MissionLog", ThisKey="MissionLogId", OtherKey="Id", IsForeignKey=true)]
		public MissionLog MissionLog
		{
			get
			{
				return this._MissionLog.Entity;
			}
			set
			{
				MissionLog previousValue = this._MissionLog.Entity;
				if (((previousValue != value) 
							|| (this._MissionLog.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MissionLog.Entity = null;
						previousValue.SquadronLogs.Remove(this);
					}
					this._MissionLog.Entity = value;
					if ((value != null))
					{
						value.SquadronLogs.Add(this);
						this._MissionLogId = value.Id;
					}
					else
					{
						this._MissionLogId = default(int);
					}
					this.SendPropertyChanged("MissionLog");
				}
			}
		}
		
		[Association(Name="FK_SquadronLogs_Persons", Storage="_Person", ThisKey="PersonId", OtherKey="PersonId", IsForeignKey=true)]
		public Person Person
		{
			get
			{
				return this._Person.Entity;
			}
			set
			{
				Person previousValue = this._Person.Entity;
				if (((previousValue != value) 
							|| (this._Person.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Person.Entity = null;
						previousValue.SquadronLogs.Remove(this);
					}
					this._Person.Entity = value;
					if ((value != null))
					{
						value.SquadronLogs.Add(this);
						this._PersonId = value.PersonId;
					}
					else
					{
						this._PersonId = default(int);
					}
					this.SendPropertyChanged("Person");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.StaticImages")]
	public partial class StaticImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _MimeType;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnMimeTypeChanging(string value);
    partial void OnMimeTypeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public StaticImage()
		{
			OnCreated();
		}
		
		[Column(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_MimeType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MimeType
		{
			get
			{
				return this._MimeType;
			}
			set
			{
				if ((this._MimeType != value))
				{
					this.OnMimeTypeChanging(value);
					this.SendPropertyChanging();
					this._MimeType = value;
					this.SendPropertyChanged("MimeType");
					this.OnMimeTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _DisplayName;
		
		private string _Email;
		
		private string _Username;
		
		private bool _Disabled;
		
		private EntityRef<Person> _Person;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    #endregion
		
		public User()
		{
			this._Person = default(EntityRef<Person>);
			OnCreated();
		}
		
		[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_FirstName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[Column(Storage="_LastName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[Column(Storage="_DisplayName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_Username", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[Column(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[Association(Name="FK_Persons_Users", Storage="_Person", ThisKey="Id", OtherKey="PersonId", IsUnique=true, IsForeignKey=false, DeleteRule="NO ACTION")]
		public Person Person
		{
			get
			{
				return this._Person.Entity;
			}
			set
			{
				Person previousValue = this._Person.Entity;
				if (((previousValue != value) 
							|| (this._Person.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Person.Entity = null;
						previousValue.User = null;
					}
					this._Person.Entity = value;
					if ((value != null))
					{
						value.User = this;
					}
					this.SendPropertyChanged("Person");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
