CREATE TABLE Pages (
   Id UNIQUEIDENTIFIER NOT NULL,
   URI NVARCHAR(50) NOT NULL,
   Title NVARCHAR(100) NOT NULL,
   Content NTEXT NOT NULL,
   BannerFileName NVARCHAR(100) NOT NULL,
   HeaderFileName NVARCHAR(100) NOT NULL,
   CONSTRAINT [PK_Pages] PRIMARY KEY CLUSTERED ([Id])
)
GO

CREATE TABLE PageStaticImages (
   PageId UNIQUEIDENTIFIER NOT NULL,
   StaticImageId UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE StaticImages (
   Id UNIQUEIDENTIFIER NOT NULL,
   MimeType NVARCHAR(50) NOT NULL,
   [Description] NVARCHAR(200) NOT NULL,
   CONSTRAINT [PK_StaticImages] PRIMARY KEY CLUSTERED ([Id])
)
GO

ALTER TABLE PageStaticImages 
    ADD CONSTRAINT FK_PageStaticImages_StaticImages
    FOREIGN KEY (StaticImageId)
    REFERENCES StaticImages
GO

ALTER TABLE PageStaticImages 
    ADD CONSTRAINT FK_PageStaticImages_Pages
    FOREIGN KEY (PageId)
    REFERENCES Pages
GO